"""add delivery tracking fields

Revision ID: 22dbb818998e
Revises: f730cbfa5f52
Create Date: 2026-01-23 19:35:31.635591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbb818998e'
down_revision = 'f730cbfa5f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('shipped_at')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
